student_name=input("Enter your name: ")
student_age=int(input("Enter your age: "))
student_grade=input("Enter your grade: ")
student_school=input("Enter your school name: ")
student_city=input("Enter your city: ")
student_country=input("Enter your country: ")
student_email=input("Enter your email address: ")
student_phone=input("Enter your phone number: ")
print("\nStudent Information:")
print("Name:", student_name)
print("Age:", student_age)
print("Grade:", student_grade)
print("School:", student_school)
print("City:", student_city)
print("Country:", student_country)
print("Email:", student_email)
print("Phone:", student_phone)